[tasks.install-hooks]
script = [
    "mkdir -p .git/hooks",
    "echo '#!/bin/sh\ncargo clippy' > .git/hooks/pre-push",
    "chmod +x .git/hooks/pre-push",
]

[tasks.deploy]
dependencies = ["build-release"]
script = [
    "sudo scp target/release/fly fly:/usr/bin/fly",
    "sudo systemctl restart fly"
]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
