[tasks.install-hooks]
script = [
    "mkdir -p .git/hooks",
    "echo '#!/bin/sh\ncargo clippy' > .git/hooks/pre-push",
    "chmod +x .git/hooks/pre-push",
]

[tasks.deploy]
dependencies = ["build-release"]
script = [
    "sudo systemctl stop fly",
    "diesel migration run",
    "sudo cp target/release/fly /usr/bin/fly",
    "sudo systemctl start fly"
]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.dashboard]
description = "Run the WTF dashboard"
script = [
    "wtfutil --config=script/dashboard/config.yml"
]
