[tasks.install-hooks]
script = [
    "mkdir -p .git/hooks",
    "echo '#!/bin/sh\ncargo clippy' > .git/hooks/pre-push",
    "chmod +x .git/hooks/pre-push"
]


[tasks.fly]
command = "cargo"
args = ["run", "--bin", "mev-eth", "--", "${@}"]
