---
- name: Configure stas user for ssh
  hosts: fly
  become: true
  vars:
    rust_home: /home/stas/.cargo
    rustup_home: /home/stas/.rustup
    rust_version: 1.84.0
  tasks:
    - name: Create fly group
      ansible.builtin.group:
        name: fly
        state: present

    - name: Create stas user
      ansible.builtin.user:
        name: stas
        groups: sudo,adm,fly
        shell: /bin/bash
        state: present
        create_home: true

    - name: Create vlad user
      ansible.builtin.user:
        name: stas
        groups: sudo
        shell: /bin/bash
        state: present
        create_home: true

    - name: Add stas to sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/stas
        line: "ALL=(ALL) NOPASSWD:ALL"
        state: present
        mode: "0440"
        create: true
        validate: "visudo -cf %s"

    - name: Create .ssh directory
      ansible.builtin.file:
        path: /home/stas/.ssh
        state: directory
        owner: stas
        group: stas
        mode: "0700"

    - name: Add SSH public keys
      ansible.builtin.template:
        src: ssh_keys/stas_rsa.pub
        dest: /home/stas/.ssh/authorized_keys
        mode: '0644'
        owner: stas
        group: stas

    - name: Copy GitHub SSH private key
      ansible.builtin.copy:
        src: /root/.ssh/fly_github
        dest: /home/stas/.ssh/id_rsa
        mode: '0600'
        owner: stas
        group: stas

    - name: Copy GitHub SSH public key
      ansible.builtin.copy:
        src: /root/.ssh/fly_github.pub
        dest: /home/stas/.ssh/id_rsa.pub
        mode: '0644'
        owner: stas
        group: stas

    - name: Set .bashrc
      ansible.builtin.blockinfile:
        path: /home/stas/.bashrc
        block: |
          export CARGO_HOME={{ rust_home }}
          export RUSTUP_HOME={{ rustup_home }}
          export DATABASE_URL=postgresql://localhost?host=/var/run/postgresql
          export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
          export OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
          export OPENSSL_INCLUDE_DIR=/usr/include/openssl
          export OPENSSL_DIR=/usr
          set -o vi
          export PS1="fly:\w$ "
          export PGUSER=fly
          export ETH_IPC_PATH=/fly/.ethereum/geth.ipc
          export ETH_IPC_URL=/fly/.ethereum/geth.ipc
          export PATH="/fly:$PATH"
          # Service log aliases
          alias j='journalctl -fu'
          alias makers="cargo make"
          export EDITOR=vim
          export BASESCAN_API_KEY={{ basescan_api_key }}
          export SLACK_OAUTH_TOKEN={{ slack_oauth_token }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - FLY ENV"
        insertafter: EOF
      become: true
      become_user: stas
