---
- name: Install and configure PostgreSQL
  hosts: all
  become: true
  tasks:
    - name: Add PostgreSQL repository key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present
        filename: pgdg


    - name: Stop PostgreSQL service if running
      ansible.builtin.service:
        name: postgresql
        state: stopped
      ignore_errors: true

    - name: Remove existing PostgreSQL service file
      ansible.builtin.file:
        path: /etc/systemd/system/postgresql.service
        state: absent

    - name: Install PostgreSQL 16
      ansible.builtin.apt:
        name:
          - postgresql-16
          - postgresql-contrib-16
        state: present
        update_cache: true

    - name: Configure pg_hba.conf for local socket connections
      ansible.builtin.copy:
        content: |
          # TYPE  DATABASE        USER            ADDRESS                 METHOD
          local   all            all                                     trust
          local   all            postgres                               trust
        dest: /etc/postgresql/16/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0600'

    - name: Copy PostgreSQL service file
      ansible.builtin.template:
        src: postgres.service.j2
        dest: /etc/systemd/system/postgresql.service
        mode: '0644'
        owner: root
        group: root

    - name: Add stas and fly users to postgres group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: postgres
        append: true
      loop:
        - stas
        - fly

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

