---
- name: Setup /fly directory and configure fly user and service
  hosts: ethereum_nodes
  become: true
  vars:
    rust_version: "1.74.0"
    fly_user: "fly"
    fly_group: "fly"

  tasks:
    - name: Create fly directory
      ansible.builtin.file:
        path: /opt/fly
        state: directory
        owner: fly
        group: fly
        mode: '0750'

    - name: Template fly environment file
      ansible.builtin.template:
        src: templates/fly.env.j2
        dest: /opt/fly/fly.env
        owner: fly
        group: fly
        mode: '0640'
      notify: Restart fly

    - name: Template fly service
      ansible.builtin.template:
        src: templates/fly.service.j2
        dest: /etc/systemd/system/fly.service
        mode: '0644'
      notify: Restart fly

    - name: Create fly system group
      ansible.builtin.group:
        name: fly
        system: true
        state: present

    - name: Create fly system user
      ansible.builtin.user:
        name: fly
        groups: fly
        system: true
        create_home: false

    - name: Add stas user to fly group
      ansible.builtin.user:
        name: stas
        groups: fly
        append: true

    - name: Create fly log directory
      ansible.builtin.file:
        path: /var/log/fly
        state: directory
        owner: fly
        group: fly
        mode: '0770'

  handlers:
    - name: Restart fly
      ansible.builtin.systemd:
        name: fly
        state: restarted
        daemon_reload: true
