---
- name: Install and configure Base node
  hosts: fly
  become: true
  vars:
    base_user: base
    base_group: fly
  tasks:
    - name: Create base system user
      ansible.builtin.user:
        name: base
        system: true
        groups:
          - base
          - fly
        append: true

    - name: Remove Base directory
      ansible.builtin.file:
        path: /opt/base
        state: absent

    - name: Clone Optimism repository
      ansible.builtin.git:
        repo: https://github.com/ethereum-optimism/optimism.git
        dest: /opt/base/optimism.git
        version: op-node/v1.10.2
        single_branch: true
        force: true


    - name: Verify commit hash
      ansible.builtin.shell:
        cmd: test "$(git rev-parse HEAD)" = "8bf7ff60f34a7c5082cec5c56bed1f76cc1893ad"
        chdir: /opt/base/optimism.git
      changed_when: false

    - name: Install just command runner
      ansible.builtin.get_url:
        url: https://just.systems/install.sh
        dest: /tmp/just-install.sh
        mode: '0755'

    - name: Install just
      ansible.builtin.command:
        cmd: bash /tmp/just-install.sh --to /usr/local/bin
        creates: /usr/local/bin/just

    - name: Build op-node
      ansible.builtin.command:
        cmd: just VERSION=v1.10.2 op-node
        chdir: /opt/base/optimism.git/op-node
        creates: /opt/base/optimism.git/op-node/bin/op-node

    - name: Copy op-node binary to /usr/bin
      ansible.builtin.copy:
        src: /opt/base/optimism.git/op-node/bin/op-node
        dest: /usr/bin/base-node
        mode: '0755'
        remote_src: true

    - name: Clone op-geth repository
      ansible.builtin.git:
        repo: https://github.com/ethereum-optimism/op-geth.git
        dest: /opt/base/op-geth.git
        version: v1.101411.4
        single_branch: true
        update: true
        clone: true
        recursive: false

    - name: Verify op-geth commit hash
      ansible.builtin.shell:
        cmd: test "$(git rev-parse HEAD)" = "efa05b1bf5c22a60745e638ad9d4adadfe3daba9"
        chdir: /opt/base/op-geth.git
      changed_when: false

    - name: Build op-geth
      ansible.builtin.command:
        cmd: go run build/ci.go install -static ./cmd/geth
        chdir: /opt/base/op-geth.git
        creates: /opt/base/op-geth.git/build/bin/geth

    - name: Copy op-geth binary to /usr/bin
      ansible.builtin.copy:
        src: /opt/base/op-geth.git/build/bin/geth
        dest: /usr/bin/base-geth
        mode: '0755'
        remote_src: true

    - name: Create Base data directory
      ansible.builtin.file:
        path: /opt/base/data
        state: directory
        owner: base
        group: base
        mode: '0755'

    - name: Create base-node.service
      ansible.builtin.template:
        src: templates/base-node.service.j2
        dest: /etc/systemd/system/base-node.service
        mode: '0644'

    - name: Create base-geth.service
      ansible.builtin.template:
        src: templates/base-geth.service.j2
        dest: /etc/systemd/system/base-geth.service
        mode: '0644'

    - name: Create base-geth-ipc-permissions.service
      ansible.builtin.template:
        src: templates/base-geth-ipc-permissions.service.j2
        dest: /etc/systemd/system/base-geth-ipc-permissions.service
        mode: '0644'

    - name: Create base-geth-ipc-permissions.path
      ansible.builtin.template:
        src: templates/base-geth-ipc-permissions.path.j2
        dest: /etc/systemd/system/base-geth-ipc-permissions.path
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start and enable base-node service
      ansible.builtin.systemd:
        name: base-node
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Start and enable base-geth service
      ansible.builtin.systemd:
        name: base-geth
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Start and enable base-geth-ipc-permissions path
      ansible.builtin.systemd:
        name: base-geth-ipc-permissions.path
        state: started
        enabled: true
        daemon_reload: true

    - name: Restart base-geth-ipc-permissions service
      ansible.builtin.systemd:
        name: base-geth-ipc-permissions.service
        state: restarted
        daemon_reload: true

