ethereum_nodes:
  hosts:
    fly:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    slack_oauth_token: "{{ lookup('env', 'SLACK_OAUTH_TOKEN') }}"
    basescan_api_key: "{{ lookup('env', 'BASESCAN_API_KEY') }}"
    etherscan_api_key: "{{ lookup('env', 'ETHERSCAN_API_KEY') }}"