---
- name: Install and configure PostgreSQL
  hosts: fly
  become: true
  tasks:
    - name: Add PostgreSQL repository key
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repository
      ansible.builtin.apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present
        filename: pgdg

    - name: Install PostgreSQL 17 packages
      ansible.builtin.apt:
        name:
          - postgresql-17
          - postgresql-contrib-17
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: pg_install
      notify: Restart PostgreSQL

    - name: Configure pg_hba.conf for local socket connections
      ansible.builtin.copy:
        content: |
          # TYPE  DATABASE        USER            ADDRESS                 METHOD
          local   all            all                                     trust
          local   all            postgres                               trust
        dest: /etc/postgresql/17/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0600'
      notify: Restart PostgreSQL

    - name: Add DATABASE_URL to /etc/profile.d
      ansible.builtin.lineinfile:
        path: /etc/profile.d/database.sh
        create: true
        line: 'export DATABASE_URL=postgresql://fly@localhost?host=/var/run/postgresql'
        mode: '0644'
        owner: root
        group: root

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
