// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `factories` table.
    ///
    /// (Automatically generated by Diesel.)
    factories (id) {
        /// The `id` column of the `factories` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `address` column of the `factories` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Varchar,
        /// The `last_pair_id` column of the `factories` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        last_pair_id -> Nullable<Int4>,
    }
}

diesel::table! {
    /// Representation of the `pairs` table.
    ///
    /// (Automatically generated by Diesel.)
    pairs (id) {
        /// The `id` column of the `pairs` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `address` column of the `pairs` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Varchar,
        /// The `token0_id` column of the `pairs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        token0_id -> Nullable<Int4>,
        /// The `token1_id` column of the `pairs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        token1_id -> Nullable<Int4>,
        /// The `factory_id` column of the `pairs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        factory_id -> Nullable<Int4>,
        /// The `reserve0` column of the `pairs` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        reserve0 -> Nullable<Numeric>,
        /// The `reserve1` column of the `pairs` table.
        ///
        /// Its SQL type is `Nullable<Numeric>`.
        ///
        /// (Automatically generated by Diesel.)
        reserve1 -> Nullable<Numeric>,
        /// The `usd` column of the `pairs` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        usd -> Nullable<Int4>,
    }
}

diesel::table! {
    /// Representation of the `tokens` table.
    ///
    /// (Automatically generated by Diesel.)
    tokens (id) {
        /// The `id` column of the `tokens` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `address` column of the `tokens` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Varchar,
        /// The `symbol` column of the `tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        symbol -> Nullable<Varchar>,
        /// The `name` column of the `tokens` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Nullable<Varchar>,
        /// The `decimals` column of the `tokens` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        decimals -> Nullable<Int4>,
    }
}

diesel::joinable!(pairs -> factories (factory_id));

diesel::allow_tables_to_appear_in_same_query!(factories, pairs, tokens,);
